// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALP0txEEZdVK10ftfdTdhn75DfRnOmgyw',
    appId: '1:853890329153:web:9d34b543c533329f36f4c0',
    messagingSenderId: '853890329153',
    projectId: 'chyaddress',
    authDomain: 'chyaddress.firebaseapp.com',
    storageBucket: 'chyaddress.firebasestorage.app',
    measurementId: 'G-38X74RS90Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5CNptng_FVS_-km0p0Neh8J3l0mm2wpY',
    appId: '1:853890329153:android:19786aff8eba13c636f4c0',
    messagingSenderId: '853890329153',
    projectId: 'chyaddress',
    storageBucket: 'chyaddress.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZDf0rhhUNuoFQs6_Jbw6__XXVyZ9Eiq0',
    appId: '1:853890329153:ios:857fce2662cc57b736f4c0',
    messagingSenderId: '853890329153',
    projectId: 'chyaddress',
    storageBucket: 'chyaddress.firebasestorage.app',
    iosBundleId: 'kr.swcore.chyaddr',
  );
}
